services:
  fastapi: 
    build: fastapi 
    ports:  # the port mappings between the host machine and the container
      - "8000:8000" # map host's port 80 to container's 8000
    env_file: #  specify one or more files that contain environment variables
      - .env 
    networks:
      - app-network
    volumes: # specify a volume mount (VOLUME:CONTAINER_PATH), or an access mode (VOLUME:CONTAINER_PATH:ACCESS_MODE).
      - /Users/ankitjain/.ssh/GCP_msds692_class_examples_key.json:/tmp/gcp-key.json
  streamlit:
    build: streamlit # build from a Dockerfile in streamlit folder
    ports:
      - "8501:8000"
    networks:  #  Specify which networks the containers for that service should connect to/communicate with.
      - app-network
    env_file: #  specify one or more files that contain environment variables
      - ./.env 
    volumes:
      - /Users/ankitjain/.ssh/GCP_msds692_class_examples_key.json:/tmp/gcp-key.json
  cron:
    build: crontab
    depends_on: # To control the order of service startup and shutdown.
      - fastapi # depends on it
    networks:
      - app-network # name of the network
networks: # Networks let services communicate with each other
  # By default, services can all communicate.
  app-network: # In this case, we don't actually need extra network. 
